# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r Pipeline/requirements.txt

# Run the Python script
CMD ["python", "Pipeline/ehd_datapipeline.py"]
