# Use an official Python image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy everything except ignored files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install python-dotenv to handle environment variables
RUN pip install python-dotenv

# Use .env file instead of hardcoded ENV values
CMD ["sh", "-c", "export $(grep -v '^#' .env | xargs) && python src/pipeline.py"]

